name: "C++ CI Release Build"

on:
  push:
    branches:
      - tasks/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Prepare Build Environment
        run: sudo apt-get update && sudo apt-get install libboost-test-dev -y

      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON

      - name: Build
        run: cmake --build .

      - name: Test
        run: cmake --build . --target test

      - name: Package
        run: cmake --build . --target package

      - name: Get Package Filename
        id: package
        run: echo "deb=$(find . -name '*.deb' -exec basename {} \; | tail -n 1)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.package.outputs.deb }}
          asset_name: ${{ steps.package.outputs.deb }}
          asset_content_type: application/vnd.debian.binary-package
